### ISSUE TITLE
quiz navigation disappear when Safe Exam Browser enabled

### ISSUE THREAD

**Issue by ihyaksm** [willianmano/moodle-theme_moove#162]
Hi,
we have problem , quiz navigation not visible when Safe Exam Browser extra restriction  enabled
moodle 3.6.3+
moove 3.6.4
![navlost](https://user-images.githubusercontent.com/50066179/56872243-f7460580-6a50-11e9-88d7-9516df35dcc6.png)

**Comment by iMarseilLe** [comment]
Hello! The same problem at 3.6.3 moodle and 3.6.4 moove version.
Works with other themes as boost and adaptive, but Moove is good at me.

**Comment by khushbu-nathani** [comment]
I have corrected this by adding below CSS

```css
#page-mod-quiz-attempt  #region-main {
	padding: 1.25rem;
}

#page-mod-quiz-attempt  [data-region="blocks-column"] {
	width: 360px;
	float: right;
	top: 0px;
	right: 0px;
	background-color: #eef5f9;
	position: relative;
	height: calc(100% - 0px);
	overflow-y: inherit;
}
```
