### ISSUE TITLE
Moodle 3.7 - Quiz Navigation Block

### ISSUE THREAD

**Issue by khushbu-nathani** [willianmano/moodle-theme_moove#167]
First of all thank you very much for awesome theme.

Moodle Quiz Navigation block is complete off the screen when attempting quiz as 'Full Screen Pop-up with Some Java-Script Security'

I have compare CSS with BOOST them and corrected by adding following additional Javascript from theme setting:

```CSS
#page-mod-quiz-attempt  #region-main {
	padding: 1.25rem;
}

#page-mod-quiz-attempt  [data-region="blocks-column"] {
	width: 360px;
	float: right;
	top: 0px;
	right: 0px;
	background-color: #eef5f9;
	position: relative;
	height: calc(100% - 0px);
	overflow-y: inherit;
}
```
