### ISSUE TITLE
List view on home page

### ISSUE THREAD

**Issue by merovingian-code** [willianmano/moodle-theme_moove#469]
**Is your feature request related to a problem? Please describe.**
In a way. The home page deck view on mobile devices does not look good

**Describe the solution you'd like**
It would be nice to have the ability to switch to list view of the courses on the homepage, similiar to "My Courses"

**Describe alternatives you've considered**
Trying a new theme that allows the customization, or editing backend CSS myself

**Additional context**
Not at this time.

**Comment by merovingian-code** [comment]
![image](https://github.com/user-attachments/assets/997bf03a-cdbb-4170-83d0-38c236eb5dc2)

**Comment by merovingian-code** [comment]
![image](https://github.com/user-attachments/assets/d9cdc4c9-029b-45f3-a5e7-92872552ebfa)

**Comment by merovingian-code** [comment]
I need to some assistance in fixing this. This is unusable on mobile.

**Comment by merovingian-code** [comment]
```css
.card-deck {
    display: inline;
}
.pagelayout-frontpage .dashboard-card, .pagelayout-coursecategory .dashboard-card {
    position: relative;
    width: calc(100% - 2rem)!important;
    max-width: calc(100% - 2rem)!important;
    margin: 1rem;
}
```
Adding this made it look like this.

![image](https://github.com/user-attachments/assets/d7e828d7-a1ae-4e2c-aa68-a8f55080b19d)
